services:
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: devfellipe
      MYSQL_USER: fellipe
      MYSQL_PASSWORD: academy
    ports:
      - "3307:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
  devdojo-db:
