spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.dev.fellipe.anime_service: debug

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20
database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  usernmae: ${LOCAL_USERNAME:root}
  password: ${LOCAL_PASSWORD:root}
